CREATE DATABASE IF NOT EXISTS discgolfapp
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_estonian_ci;
USE discgolfapp;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS discs;
DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS user_discs;
DROP TABLE IF EXISTS multiplayer_games;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL,
    active BOOLEAN DEFAULT TRUE,
    user_role ENUM('user', 'admin') NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE courses (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    course_name VARCHAR(255) NOT NULL UNIQUE,
    course_location VARCHAR(255),
    holes INT CHECK (holes > 0),
    par INT CHECK (par > 0),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE discs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    disc_type VARCHAR(50) CHECK (disc_type IN ('Putter', 'Midrange', 'Driver')),
    speed DECIMAL(2,0) CHECK (speed BETWEEN 1 AND 14),
    glide DECIMAL(2,0) CHECK (glide BETWEEN 1 AND 7),
    turn DECIMAL(3,1) CHECK (turn BETWEEN -5 AND 1),
    fade DECIMAL(2,0) CHECK (fade BETWEEN 0 and 5),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE games (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    course_id INT UNSIGNED NULL,
    date_played TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INT UNSIGNED NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT fk_games_course
        FOREIGN KEY (course_id) REFERENCES courses(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_games_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE user_discs (
    user_id INT UNSIGNED NOT NULL,
    disc_id INT UNSIGNED NOT NULL,
    added_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (user_id, disc_id),
    CONSTRAINT fk_userdiscs_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_userdiscs_disc
        FOREIGN KEY (disc_id) REFERENCES discs(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE multiplayer_games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    game_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    score INT NOT NULL,
    user_status ENUM('active', 'removed') NOT NULL DEFAULT 'active',
    left_at TIMESTAMP NULL DEFAULT NULL,
    game_status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)  ENGINE=InnoDB DEFAULT CHARSET = utf8mb4;


ALTER TABLE multiplayer_games
RENAME COLUMN status TO status;
